# Generated by Django 5.2.1 on 2025-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maildate', models.DateField()),
                ('ou_invoice_url', models.CharField(max_length=255, unique=True)),
                ('in_invoice_url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'invoiceinfo',
            },
        ),
        migrations.CreateModel(
            name='McGrath_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_url', models.CharField(max_length=255, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('part_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ordered', models.CharField(blank=True, max_length=50, null=True)),
                ('supplied', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_List', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_Net', models.CharField(blank=True, max_length=50, null=True)),
                ('GST_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mcgrath_invoice',
            },
        ),
        migrations.CreateModel(
            name='Wurth_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_url', models.CharField(max_length=255, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('itemno', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Ext_Net_Price_AUD', models.CharField(blank=True, max_length=50, null=True)),
                ('Price_Unit', models.CharField(blank=True, max_length=50, null=True)),
                ('Price_AUD', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('Pack_Unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wurth_invoice',
            },
        ),
    ]
