# Generated by Django 5.2.1 on 2025-06-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('part_description', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=100)),
                ('trade_price', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('purchase_count', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('selling_price_exc_gst', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('selling_price_inc_gst', models.IntegerField()),
            ],
            options={
                'db_table': 'purchasereport',
            },
        ),
        migrations.DeleteModel(
            name='McGrath_Invoice',
        ),
        migrations.DeleteModel(
            name='Wurth_invoice',
        ),
    ]
