# Generated by Django 5.2.1 on 2025-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_purchasereport_delete_mcgrath_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDownloaded_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maildate', models.DateField()),
            ],
        ),
    ]
