# Generated by Django 5.2.1 on 2025-06-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_supplier_calculationcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationcase',
            old_name='case',
            new_name='case_name',
        ),
        migrations.AddField(
            model_name='calculationcase',
            name='condition',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
