# Generated by Django 5.2.1 on 2025-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_case_calculationcase_case_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McGrathReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('maildate', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('part_Number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('ordered', models.CharField(max_length=10)),
                ('supplied', models.CharField(max_length=10)),
                ('unit_List', models.CharField(max_length=10)),
                ('unit_Net', models.CharField(max_length=10)),
                ('GST_Code', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WurthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('maildate', models.DateField()),
                ('itemno', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('customer_part_no', models.CharField(max_length=100)),
                ('Ext_Net_Price_AUD', models.CharField(max_length=10)),
                ('Price_Unit', models.CharField(max_length=10)),
                ('Price_AUD', models.CharField(max_length=10)),
                ('Quantity', models.CharField(max_length=10)),
                ('Pack_Unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='YhiaustraliaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('maildate', models.DateField()),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=10)),
                ('unit_price', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
    ]
