# Generated by Django 5.2.1 on 2025-06-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mcgrathreport_wurthreport_yhiaustraliareport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_col', models.CharField(max_length=100)),
                ('date_col', models.DateField()),
                ('part_description_col', models.DateField(max_length=255)),
                ('part_number_col', models.CharField(max_length=100)),
                ('trade_price_col', models.CharField(max_length=100)),
                ('total_count_col', models.CharField(max_length=100)),
                ('purchase_count_col', models.CharField(max_length=100)),
                ('total_price_col', models.CharField(max_length=100)),
                ('actual_price_col', models.CharField(max_length=100)),
                ('profit_col', models.CharField(max_length=100)),
                ('selling_price_exc_gst_col', models.CharField(max_length=100)),
                ('gst_col', models.CharField(max_length=100)),
                ('selling_price_inc_gst_col', models.CharField(max_length=100)),
                ('column_supplier_select', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplier')),
            ],
        ),
    ]
