# Generated by Django 5.2.1 on 2025-06-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_columnmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnmapping',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='date_col',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='part_description_col',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='supplier_col',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
