# Generated by Django 5.2.1 on 2025-06-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_columnmapping_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmapping',
            name='date_col',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='part_description_col',
            field=models.CharField(max_length=100),
        ),
    ]
