# Generated by Django 5.2.1 on 2025-06-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_columnmapping_date_col_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnmapping',
            name='column_supplier_select',
        ),
    ]
