# Generated by Django 5.2.1 on 2025-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_casemodel_delete_calculationcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='actual_price',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
