# Generated by Django 5.2.1 on 2025-06-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_casemodel_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceinfo',
            name='mailsubject',
            field=models.CharField(default='null', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='supplier',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
