# Generated by Django 5.2.1 on 2025-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_scrappeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereport',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
