# Generated by Django 5.2.1 on 2025-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_purchasereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereport',
            name='date',
            field=models.DateField(),
        ),
    ]
