# Generated by Django 5.2.1 on 2025-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_purchasereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinfo',
            name='maildate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mcgrathreport',
            name='maildate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasereport',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wurthreport',
            name='maildate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yhiaustraliareport',
            name='maildate',
            field=models.CharField(max_length=100),
        ),
    ]
