# Generated by Django 5.2.1 on 2025-06-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_invoiceinfo_maildate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepcoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('maildate', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('retail_incl_gst', models.CharField(max_length=10)),
                ('unit_price_excl_gst', models.CharField(max_length=10)),
                ('qty_supplied', models.CharField(max_length=10)),
                ('total_gst', models.CharField(max_length=10)),
                ('s', models.CharField(max_length=10)),
                ('total_incl_gst', models.CharField(max_length=10)),
            ],
        ),
    ]
